---
# Ansible inventory для учебной инфраструктуры по защите ОС

all:
  children:
    linux:
      hosts:
        ubuntu-server:
          ansible_host: 192.168.100.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
    
    windows:
      hosts:
        windows-server-2016:
          ansible_host: 192.168.100.20
          ansible_user: Administrator
          ansible_password: "Admin123!"
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
        
        windows-10-pro:
          ansible_host: 192.168.100.30
          ansible_user: User
          ansible_password: "User123!"
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore

