vuln_enabled: []

vkr_vuln_linux_weak_password: "password"
vkr_vuln_linux_extra_admin_user: "testadmin"

vkr_vuln_linux_known:
  - linux.auth.weak_root_password
  - linux.auth.no_password_policy
  - linux.auth.extra_admin_user
  - linux.sudo.nopasswd
  - linux.ssh.root_login
  - linux.ssh.password_auth
  - linux.firewall.disabled
  - linux.services.insecure_telnet
  - linux.services.insecure_ftp
  - linux.files.world_writable_secrets
  - linux.updates.disabled
  - linux.logging.disabled
  - linux.cron.world_writable_cron

