- name: Disable UAC (EnableLUA=0) (requires reboot)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    data: 0
    type: dword

- name: Reboot after disabling UAC
  ansible.windows.win_reboot:
    reboot_timeout: 1800

