- name: Disable password policy (net accounts)
  ansible.windows.win_shell: |
    net accounts /minpwlen:0
    net accounts /maxpwage:unlimited
    net accounts /minpwage:0
    net accounts /uniquepw:0

