- name: Enable weak NTLM/LM compatibility (LmCompatibilityLevel=0)
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: LmCompatibilityLevel
    data: 0
    type: dword

