---
# Ansible inventory для Linux стенда

all:
  children:
    linux_workstation:
      hosts:
        linux-ws:
          ansible_host: 192.168.102.10
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3
    
    linux_server:
      hosts:
        linux-server:
          ansible_host: 192.168.102.20
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3
