- name: Enable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*PasswordAuthentication\s+'
    line: 'PasswordAuthentication yes'
    create: yes
  notify: Restart SSH

