- name: Disable SMB signing requirement (Server)
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
    name: RequireSecuritySignature
    data: 0
    type: dword

- name: Disable SMB signing (Server) (best-effort)
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
    name: EnableSecuritySignature
    data: 0
    type: dword

- name: Disable SMB signing requirement (Workstation)
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
    name: RequireSecuritySignature
    data: 0
    type: dword

- name: Disable SMB signing (Workstation) (best-effort)
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
    name: EnableSecuritySignature
    data: 0
    type: dword

