- name: Enable RDP (allow connections)
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword

- name: Enable firewall rules for Remote Desktop
  ansible.windows.win_shell: |
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
  failed_when: false

