vuln_enabled: []

vuln_windows_weak_password: "password"
vuln_windows_testadmin_user: "TestAdmin"

vuln_windows_known:
  - windows.auth.lockout_disabled
  - windows.auth.weak_admin_password
  - windows.auth.no_password_policy
  - windows.auth.guest_enabled
  - windows.priv.testadmin_in_admins
  - windows.remote.rdp_enabled
  - windows.firewall.disabled
  - windows.updates.disabled
  - windows.defender.disabled
  - windows.network.smb1_enabled
  - windows.network.ntlmv1_enabled
  - windows.network.llmnr_enabled
  - windows.network.smb_signing_disabled
  - windows.services.remote_registry_enabled
  - windows.uac.disabled
  - windows.desktop.no_lock_on_idle
  - windows.power.sleep_disabled
  - windows.audit.disabled

