---
- name: Disable auditing on DC (local) (best-effort)
  ansible.windows.win_shell: |
    try {
      auditpol /set /category:* /success:disable /failure:disable | Out-Null
      "OK"
    } catch {
      "SKIP/ERR"
    }
  changed_when: false
  failed_when: false

