vuln_enabled: []

vuln_linux_weak_password: "password"
vuln_linux_extra_admin_user: "testadmin"

vuln_linux_known:
  - linux.auth.lockout_disabled
  - linux.auth.weak_root_password
  - linux.auth.no_password_policy
  - linux.auth.extra_admin_user
  - linux.priv.suid_bash_backdoor
  - linux.sudo.nopasswd
  - linux.ssh.root_login
  - linux.ssh.password_auth
  - linux.ssh.no_rate_limit
  - linux.firewall.disabled
  - linux.services.insecure_telnet
  - linux.services.insecure_ftp
  - linux.files.world_writable_secrets
  - linux.files.unsafe_path_in_profile
  - linux.updates.disabled
  - linux.logging.disabled
  - linux.cron.world_writable_cron

