---
vkr_ad_org_enabled: true

vkr_ad_training_ou: "Training"
vkr_ad_stand_ou: "Stand-01"
vkr_ad_stand_id: "stand-01"

# IMPORTANT: must match COMPUTERNAME in domain (not Ansible inventory host alias)
vkr_ad_stand_computers: []

vkr_ad_gpo_prefix: "VKR-ad.gpo."

