---
# Handlers для перезапуска Samba

- name: restart samba
  systemd:
    name: smbd
    state: restarted
  become: yes

- name: restart nmbd
  systemd:
    name: nmbd
    state: restarted
  become: yes

